# Nixpacks configuration for Railway deployment with permission fix
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "cd client && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "chmod +x ./client/node_modules/.bin/react-scripts || true",
  "cd client && npm run build"
]

[start]
cmd = "npm start"
