const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

test('admissions migration is additive and preserves legacy statuses', () => {
  const migration = read('migrations/admissions_management_phase.sql');
  assert.match(migration, /ADD COLUMN IF NOT EXISTS application_reference/);
  assert.match(migration, /CREATE UNIQUE INDEX IF NOT EXISTS idx_enrollments_application_reference/);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS enrollment_status_history/);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS admissions_email_log/);
  assert.match(migration, /registration_token_hash CHAR\(64\)/);
  assert.match(migration, /SET LOCAL lock_timeout = '5s'/);
  assert.match(migration, /SET LOCAL statement_timeout = '60s'/);
  assert.match(migration, /ALTER TABLE enrollments ALTER COLUMN status SET DEFAULT 'pending'/);
  assert.match(migration, /ALTER TABLE enrollments ALTER COLUMN status TYPE VARCHAR\(40\)/);
  assert.match(migration, /WHERE application_reference IS NULL/);
  assert.match(migration, /ROW_NUMBER\(\) OVER \(ORDER BY created_at NULLS LAST, id\)/);
  assert.match(migration, /SELECT setval\(/);
  assert.match(migration, /GREATEST\(highest_reference\.highest_number \+ 1, current_sequence\.next_number, 1\)/);
  assert.match(migration, /CASE WHEN is_called THEN last_value \+ 1 ELSE last_value END/);
  assert.match(migration, /admissions_migration_id_snapshot/);
  assert.doesNotMatch(migration, /\b(?:DELETE FROM|TRUNCATE|DROP TABLE)\b/i);
  for (const legacy of ['pending', 'approved', 'rejected', 'waitlisted']) {
    assert.match(migration, new RegExp(`'${legacy}'`));
  }
});

test('release has an explicit migration command and schema readiness guard', () => {
  const script = read('scripts/run-admissions-migration.js');
  const route = read('routes/enrollments.js');
  assert.match(script, /admissions_management_phase\.sql/);
  assert.match(script, /Admissions migration applied and verified/);
  assert.match(script, /null_references/);
  assert.match(script, /duplicate_references/);
  assert.match(script, /next_sequence_is_safe/);
  assert.match(script, /statusDefault: 'pending'/);
  assert.match(route, /requireAdmissionsSchema/);
  assert.match(route, /res\.status\(503\)/);
});

test('application references are generated by the database-backed insert', () => {
  const route = read('routes/enrollments.js');
  assert.match(route, /nextval\('enrollment_application_reference_seq'\)/);
  assert.match(route, /'HLI-2027-' \|\| LPAD/);
  assert.match(route, /RETURNING \*/);
  assert.match(route, /application_reference: enrollment\.application_reference/);
});

test('confirmation emails are sent only after successful persistence', () => {
  const route = read('routes/enrollments.js');
  const insertIndex = route.indexOf('const enrollment = result.rows[0]');
  const emailIndex = route.indexOf('sendApplicationConfirmation(enrollment)');
  assert.ok(insertIndex > -1 && emailIndex > insertIndex);
  assert.match(route, /Application .* saved; .* email failed/);
  assert.match(route, /logEmailDelivery\(enrollment\.id/);
});

test('status updates are controlled, transactional, audited, and idempotent', () => {
  const route = read('routes/enrollments.js');
  assert.match(route, /ADMISSIONS_STATUSES\.includes\(status\)/);
  assert.match(route, /SELECT \* FROM enrollments WHERE id = \$1 FOR UPDATE/);
  assert.match(route, /if \(current\.status === status\)/);
  assert.match(route, /statusChanged: false/);
  assert.match(route, /INSERT INTO enrollment_status_history/);
  assert.match(route, /action: 'admissions_status_change'/);
  assert.match(route, /sendAdmissionsStatusEmail\(\s*enrollment,\s*status/);
  assert.doesNotMatch(route, /router\.delete\('\/:id'/);
});

test('registration tokens use cryptographic randomness, hashing, and expiry', () => {
  const {
    generateRegistrationToken,
    hashRegistrationToken,
    registrationTokenExpiry,
  } = require('../utils/admissions');
  const first = generateRegistrationToken();
  const second = generateRegistrationToken();
  assert.notEqual(first, second);
  assert.equal(hashRegistrationToken(first).length, 64);
  const issued = new Date('2027-01-01T00:00:00Z');
  assert.equal(registrationTokenExpiry(issued).toISOString(), '2027-01-08T00:00:00.000Z');
});

test('parent email templates exclude internal notes and cover required statuses', () => {
  const { statusEmailContent, escapeHtml } = require('../services/gmailService');
  assert.equal(escapeHtml('<private>'), '&lt;private&gt;');
  for (const status of ['UNDER_REVIEW', 'MORE_INFORMATION_REQUIRED', 'APPROVED', 'REGISTRATION_PENDING', 'REGISTERED', 'NOT_ACCEPTED']) {
    const content = statusEmailContent(status, 'HLI-2027-0001', 'Parent-safe update');
    assert.ok(content.subject.includes('HLI-2027-0001'));
    assert.ok(content.html.includes('Parent-safe update'));
    assert.ok(!content.html.includes('admin_notes'));
  }
  assert.equal(statusEmailContent('NEW', 'HLI-2027-0001'), null);
});

test('public Student Portal links are removed while Parent and Staff remain', () => {
  const landing = read('client/src/components/public/LandingPage.js');
  assert.doesNotMatch(landing, /title="Student Portal"/);
  assert.doesNotMatch(landing, />Student Portal<\/Link>/);
  assert.match(landing, /title="Parent Portal"/);
  assert.match(landing, /title="Staff Portal"/);
  assert.match(landing, /application_reference/);
});

test('Admin admissions UI includes reference, search, statuses and no delete action', () => {
  const admin = read('client/src/components/admin/EnrollmentManagement.js');
  assert.match(admin, /Search reference, learner, parent, email or phone/);
  assert.match(admin, /application_reference/);
  assert.match(admin, /ADMISSIONS_STATUSES\.map/);
  assert.match(admin, /Parent-safe message/);
  assert.match(admin, /Status history/);
  assert.match(admin, /Use Request more information to send a targeted request/);
  assert.match(admin, /filter\(\(\{ value \}\) => value !== 'MORE_INFORMATION_REQUIRED'\)/);
  assert.match(admin, /!nextStatus/);
  assert.doesNotMatch(admin, /handleDelete|title="Delete"/);
});