import React, { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { BookOpen, CheckCircle } from 'lucide-react';
import toast from 'react-hot-toast';
import ParentPasswordRequirements, { passwordIsValid } from './ParentPasswordRequirements';

const ParentResetPassword = () => {
  const [params] = useSearchParams(); const token = params.get('token') || ''; const navigate = useNavigate();
  const [valid, setValid] = useState(token ? true : false); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async e => { e.preventDefault(); if (!passwordIsValid(password)) return toast.error('Password must be at least 8 characters.'); if (password !== confirm) return toast.error('Passwords do not match.'); setSaving(true); try { const r = await fetch('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, password, new_password: password }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.message || 'Unable to reset password.'); setValid('done'); } catch (err) { toast.error(err.message); } finally { setSaving(false); } };
  return <div className="min-h-screen bg-gradient-to-br from-blue-900 via-blue-800 to-red-700 flex items-center justify-center p-4"><div className="w-full max-w-md"><div className="text-center mb-7"><BookOpen className="mx-auto h-12 w-12 text-white mb-3" /><h1 className="text-2xl font-bold text-white">Reset Parent Password</h1></div><div className="bg-white rounded-2xl shadow-2xl p-7">{valid === null ? <p className="text-center py-8 text-gray-500">Checking your secure link…</p> : valid === false ? <div className="text-center text-gray-600"><p className="mb-5">This reset link is invalid or expired.</p><button onClick={() => navigate('/parent/forgot-password')} className="w-full py-3 bg-blue-600 text-white rounded-xl font-semibold">Request a new link</button></div> : valid === 'done' ? <div className="text-center py-5"><CheckCircle className="mx-auto text-emerald-600 mb-3" size={48} /><h2 className="font-bold text-gray-800">Password updated</h2><p className="text-sm text-gray-500 mt-2 mb-5">You can now sign in to your parent portal.</p><button onClick={() => navigate('/parent/login')} className="w-full py-3 bg-blue-600 text-white rounded-xl font-semibold">Go to login</button></div> : <form onSubmit={submit} className="space-y-4"><div><label className="block text-sm font-medium mb-1">New password</label><input required type="password" value={password} onChange={e => setPassword(e.target.value)} className="w-full px-4 py-3 border rounded-xl" autoComplete="new-password" /><ParentPasswordRequirements password={password} /></div><div><label className="block text-sm font-medium mb-1">Confirm password</label><input required type="password" value={confirm} onChange={e => setConfirm(e.target.value)} className="w-full px-4 py-3 border rounded-xl" autoComplete="new-password" /></div><button disabled={saving} className="w-full py-3 bg-blue-600 text-white rounded-xl font-semibold disabled:opacity-60">{saving ? 'Saving…' : 'Save new password'}</button></form>}</div></div></div>;
};
export default ParentResetPassword;